### ISSUE TITLE
PS4 controller teleop not yet working

### ISSUE THREAD

**Issue by nickswalker** [homeskies/uw_robocup#4]
Fetch recommends using a PS4 controller under 18.04, so we've got one and we've stepped through [the configuration](https://docs.fetchrobotics.com/ps4.html), but something is going awry in the middle part of the pipeline. I recall being able to see the controller output from the `/dev/joy` (or whatever) file, but it wasn't making it up to the ROS joy node.

**Comment by podshara** [comment]
PS4 controller is now working. I've test that the controller for move base, move head, move torso, gripper and arm are all working correctly.
