### ISSUE TITLE
Complete arena wall panels

### ISSUE THREAD

**Issue by nickswalker** [homeskies/uw_robocup#6]
So we can prep a map

**Comment by nickswalker** [comment]
@csemecu I would like to have the walls filled out before the weekend. Let me know when you're available and I can help

**Comment by csemecu** [comment]
I'm actually filling them out after class today.

You don't have to stay :) I already asked Stephanie for help. But thanks
for offering to help

**Comment by csemecu** [comment]
The walls are up!

I ran out of tape yesterday to finish the details in one of the corners, and I will get that sorted. But the rest is pretty much done.
